# Generated by Django 4.1.7 on 2023-02-24 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.PositiveBigIntegerField(default=9999999999)),
                ('contact_person', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='default address', max_length=200)),
                ('gst', models.CharField(default='07AAWFR0503R1ZK', max_length=15)),
                ('pan_no', models.CharField(default='AABCI6154K', max_length=15)),
                ('owners_name', models.CharField(default='', max_length=50)),
                ('owners_email', models.EmailField(default='', max_length=50)),
                ('owners_birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fees', models.IntegerField(default=100000)),
                ('documents', models.FileField(blank=True, default='N/A', null=True, upload_to='media/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
