# Generated by Django 4.1.7 on 2023-02-24 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(unique=True)),
                ('contact', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Franchise Admin', 'Franchise Admin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Associate', 'Associate')], default='Associate', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.PositiveBigIntegerField(default=9999999999)),
                ('contact_person', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='default address', max_length=200)),
                ('gst', models.CharField(default='07AAWFR0503R1ZK', max_length=15)),
                ('pan_no', models.CharField(default='AABCI6154K', max_length=15)),
                ('owners_name', models.CharField(default='', max_length=50)),
                ('owners_email', models.EmailField(default='', max_length=50)),
                ('owners_birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fees', models.IntegerField(default=100000)),
                ('documents', models.FileField(blank=True, default='N/A', null=True, upload_to='media/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_companies',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_companies', to='user.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
