# Generated by Django 4.1.7 on 2023-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0005_rename_is_staff_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_companies',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_companies', to='company.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
